name: WelcomeMessage
main: me.cr3dossoft.WelcomeMessage.WelcomeMessage
version: 1.5
author: cr3dos
description: >
             Welcome the Players on your server
commands:
  welcome:
    description: toggle WelcomeMessage
    usage: /welcome
  wmset:
    description: set message for group
    usage: /wmset <groupname> <new Message>